package com.intbyte.bw.gameAPI.environment.json_wrapper;

import com.intbyte.bw.gameAPI.environment.*;
import com.intbyte.bw.gameAPI.physic.PhysicBlockObject;
import com.badlogic.gdx.math.Rectangle;
import com.intbyte.bw.gameAPI.utils.Resource;

//do not delete, this file was automatically generated by json data generator from json files
public class GeneratedJsonData{
    public static void init(){
        BlockWrapper blockWrapper = new BlockWrapper();
        Block.CustomBlock block;
        PhysicBlockObject object = new PhysicBlockObject();
        object.setShape(new Rectangle(0,0,20,20));
        object.setOffset(10, 10);
        Resource.putBlockObject("10x10",object);
                
        blockWrapper.reset();
        blockWrapper.setId("grass");
		blockWrapper.setModel("_stone_3.g3db");
		blockWrapper.setTexture("Ekfs_bush_map.png");
		blockWrapper.setHealth(100);
		blockWrapper.setBody(object);
		blockWrapper.setIconScale(0.1f);
		blockWrapper.setType(Block.STONE);
		blockWrapper.setLevel(100);
		block = Block.defineBlock(blockWrapper);
		block.updateIcon();
		block.setScale(0.1f);
    }
}